[package]
name = "red_primality"
version = "0.1.0"
authors = ["Ken Bateman <novadenizen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
primal = "0.2.3"
